wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
activation:
  desc: null
  value: relu
hidden_layer:
  desc: null
  value:
  - 10
  - 15
  - 10
Optimizer:
  desc: null
  value: Batch
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698000598.374128
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
